version: '3.4'

services:
  backend_app:
    image: djangovoting
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 voting_app.wsgi"
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend:/backend
  frontend_app:
    image: node:16.14.0
    environment:
      - NODE_ENV=development
    command: npm start
    ports:
      - '3000:3000'
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
