# Generated by Django 5.1.2 on 2024-11-02 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, help_text="Timestamp when record was updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Use this boolean to soft-delete the record.",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("voters", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Survey",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, help_text="Timestamp when record was updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Use this boolean to soft-delete the record.",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("votes", models.IntegerField(default=0)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Question",
            },
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, help_text="Timestamp when record was updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Use this boolean to soft-delete the record.",
                    ),
                ),
                ("code", models.CharField(max_length=4)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Code",
            },
        ),
    ]
