# Generated by Django 4.1.5 on 2024-10-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="code",
            old_name="question",
            new_name="code",
        ),
    ]
