# Generated by Django 4.1.5 on 2024-10-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_rename_question_code_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="voters",
            field=models.IntegerField(default=0),
        ),
    ]
